version: '3'
services:
    web:
        image: server
        container_name: serving_box
        command: bash -c "gunicorn myproject.wsgi:application -b 0.0.0.0:8000" # 서버 실행
        ports:
            - '8000:8000'
        restart: always
        volumes:
            - .:/app
            - ./static:/app/static
            - ./media:/app/media
        networks:
            - server

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
            - ./static:/static
            - ./media:/media # media가 있으면
            - ./cert/certbot/conf:/etc/letsencrypt # 이 부분
            - ./cert/certbot/www:/var/www/certbot # 이 부분
        restart: always
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - web
        networks:
            - server

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./cert/certbot/conf:/etc/letsencrypt
            - ./cert/certbot/www:/var/www/certbot
        command: certonly --webroot --webroot-path=/var/www/certbot --email your@email.com --agree-tos --no-eff-email -d luxurylion.site
        depends_on:
            - nginx

networks:
    server:
    driver: bridge
